apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
  spec:
    containers:
    - name: webapp
      image: subha1985/test  
      ports:
      - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: webapp-service  
  labels:
    app: webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: NodePort
