---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: http
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: http
  template:
    metadata:
      labels:
        app: http
  spec:
    containers:
    - name: http
      image: subha1985/test
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: http
  spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: http
  type: NodePort

