---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
  spec:
    containers:
    - name: httpd
      image: subha1985/test
      ports:
      - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: httpd
spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 80
 selector:
  app: httpd
 type: NodePort

